site_name: Azolyzer
site_author: Azorimor
site_description: Azolyzer analyze discord server statistics.
repo_url: https://github.com/Azorimor/azolyzer
theme:
  name: material
  favicon: ../azolyzer-docs/assets/favicon.png
  palette:
    scheme: preference
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/azorimor
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/azorimor
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/azorimor
    - icon: fontawesome/brands/github
      link: https://github.com/azorimor
plugins:
  - search
markdown_extensions:
  - attr_list
google_analytics: ['UA-142181342-2','auto']
nav:
  - Home: index.md
  - Contribute: ./contribute/index.md