site_name: Azolyzer Documentation - Discord Server Bot Anylytics
site_author: Azorimor
site_description: Azolyzer analyze and collect discord server statistics.
site_url: https://azorimor.github.io/azolyzer-docs/
repo_url: https://github.com/Azorimor/azolyzer-docs
theme:
  name: material
  favicon: ../azolyzer-docs/assets/favicon.png
  palette:
    scheme: preference
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/azorimor
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/azorimor
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/azorimor
    - icon: fontawesome/brands/github
      link: https://github.com/azorimor
plugins:
  - search
markdown_extensions:
  - attr_list
nav:
  - Home: index.md
  - Self hosting:
    - Information: ./self-hosting/index.md
    - Deploy: ./self-hosting/deploy.md
    - Environment: ./self-hosting/environment.md
  - Contribute: 
    - Bot: ./contribute/bot.md
    - Docs: ./contribute/docs.md