site_name: Azorimor-DB
repo_url: https://github.com/Azorimor/azolyzer
theme:
  name: material
  palette:
    scheme: preference
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/azorimor
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/azorimor
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/azorimor
    - icon: fontawesome/brands/github
      link: https://github.com/azorimor
plugins:
  - search
nav:
  - Home: index.md
  - Contribute: ./contribute/index.md